# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - nuget restore src\vcsparser.sln

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


platform: Any CPU
configuration: Release

build:
  parallel: true              
  project: src\vcsparser.sln  

before_build:

build_script:

after_build:

before_package:

test_script:  
  - .\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\src\packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.x86.exe" -targetargs:".\src\vcsparser.unittests\bin\Release\vcsparser.unittests.dll .\src\vcsparser.PowerShell.unittests\bin\Release\vcsparser.PowerShell.unittests.dll .\src\vcsparser.bugdatabase.azuredevops.unittests\bin\Release\vcsparser.bugdatabase.azuredevops.unittests.dll -noshadow" -output:"coverage.xml" -filter:"+[vcsparser.core*]* -[vcsparser.*unittests*]* +[vcsparser.PowerShell*]* -[vcsparser.PowerShell]vcsparser.PowerShell.CmdletAdapter +[vcsparser.bugdatabase*]* -[vcsparser.bugdatabase.azuredevops]vcsparser.bugdatabase.azuredevops.AzureDevOpsFactory -[vcsparser.core]vcsparser.core.bugdatabase.BugDatabaseFactory -[vcsparser.core]vcsparser.core.bugdatabase.HttpClientWrapper"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 565df92a-14b9-4de0-bf28-72c4946fd4b4

artifacts:

  # pushing entire folder as a zip archive
  - path: src\vcsparser\bin\Release

notifications:  
  - provider: Email
    to:
      - ericlemes@gmail.com        